INSERT INTO gmadb.QUESTION (ID,POINTS,`TEXT`)
	VALUES (2,1,'Sex');
INSERT INTO gmadb.QUESTION (ID,POINTS,`TEXT`)
	VALUES (1,1,'Age');
INSERT INTO gmadb.QUESTION (ID,POINTS,`TEXT`)
	VALUES (3,1,'Expertise');
