DELIMITER $$
USE `gmadb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `gmadb`.`answer_AFTER_INSERT` AFTER INSERT ON `ANSWER` FOR EACH ROW
BEGIN
update CONSUMER 
	set points =  
				(SELECT * FROM (SELECT POINTS 
                FROM CONSUMER
                WHERE USERNAME=new.USER_ID) as C1) + (SELECT POINTS 
												FROM QUESTION 
												WHERE QUESTION.ID=new.QUESTION_ID)
			WHERE USERNAME=new.USER_ID;

END$$
DELIMITER ;

DELIMITER $$
USE `gmadb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `gmadb`.`answer_AFTER_DELETE` AFTER DELETE ON `ANSWER` FOR EACH ROW
BEGIN
update CONSUMER 
	set points =  
				(SELECT * FROM (SELECT POINTS 
                FROM CONSUMER
                WHERE USERNAME=old.USER_ID) as C1) - (SELECT POINTS 
												FROM QUESTION 
												WHERE QUESTION.ID=old.QUESTION_ID)
			WHERE USERNAME=old.USER_ID;
END$$
DELIMITER ;

DELIMITER $$
USE `gmadb` $$
CREATE DEFINER = CURRENT_USER TRIGGER `gmadb`.`questionnaire_AFTER_INSERT` AFTER INSERT ON `QUESTIONNAIRE` FOR EACH ROW
BEGIN
insert INTO QUESTIONNAIRE_QUESTION (QUESTION_ID, QUESTIONNAIRE_ID) VALUES (1, new.DATE);
insert INTO QUESTIONNAIRE_QUESTION (QUESTION_ID, QUESTIONNAIRE_ID) VALUES (2, new.DATE);
insert INTO QUESTIONNAIRE_QUESTION (QUESTION_ID, QUESTIONNAIRE_ID) VALUES (3, new.DATE);
END$$
DELIMITER ;
